apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: ml-serving
type: Opaque
data:
  GITHUB_TOKEN: Z2l0aHViX3BhdF8xMUFTNFM2WlkweFVrRzluMmVJM25sX21VYTh0eGRjblFQWHBPcE5IUlg1d1VuT0tjZldDZ1o4NG9nZkZ2RU9BYW5EWFdLSVVZNzd1akNsYnB0

