
apiVersion: v1
kind: Service
metadata:
  name: ml-serving-pod-controller-service
  namespace: ml-serving
spec:
  selector:
    app: ml-serving-pod-controller-server
  ports:
    - protocol: TCP
      port: 8000  # 服務的 Port
      targetPort: 8000  # 轉發到 Container 內部的 Port
      nodePort: 30008  # 讓外部可以透過這個 Port 存取
  type: NodePort  # 讓外部可以透過 <minikube-ip>:38000訪問
  # type: ClusterIP  # 預設值，可省略



