apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: ml-serving
type: Opaque
data:
  # base64(minio)
  AWS_ACCESS_KEY_ID: bWluaW8=   
  # base64(minio123)
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=  
